name: Inject CSP hashes

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  inject-csp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Inject CSP
        run: node scripts/inject-csp.js
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add nginx/default.conf
          git commit -m "ci: inject CSP hashes into nginx/default.conf" || echo "no changes"
          git push
